#!/bin/bash

#set -x

verb=$1
app=$2
path=/`echo $app | tr "." "/"`

usage() {
	echo "Usage: appctl [activate-action|quit|start]"
}

if [ -z $verb ]; then
	usage
	exit 1
fi

case "$verb" in
	activate-action)
		action="$3"
		if [ -n "$4" ]; then
			param="<$4>"
		else
			param=""
		fi
		gdbus call --session --dest $app --object-path $path	\
			--method org.freedesktop.Application.ActivateAction "'$action'" "[$param]" "{$XDG_PLATFORM_DATA}"
		;;
	quit)
		exec $0 activate-action $2 quit
		;;
	start)
		gdbus call --session --dest $app --object-path $path \
			--method org.freedesktop.Application.Activate "{$XDG_PLATFORM_DATA}"
		;;
	help)
		usage
		;;
	*)
		usage
		exit 1
esac


